// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"frame/app/customer/internal/biz"
	"frame/app/customer/internal/conf"
	"frame/app/customer/internal/data"
	"frame/app/customer/internal/server"
	"frame/app/customer/internal/service"
	"frame/pkg/appmanage"
)

// Injectors from wire.go:

func initApp(db *conf.ConfDB, http *conf.HttpConf, grpc *conf.GrpcConf) *appmanage.AppManage {
	fakeDB := data.NewBD(db)
	customerRepo := data.NewCustomerRepo(fakeDB)
	customerUsecase := biz.NewCustomerUsecase(customerRepo)
	customerService := service.NewCustomerService(customerUsecase)
	httpServer := server.NewHttpServer(customerService, http)
	grpcServer := server.NewGrpcServer(customerService, grpc)
	appManage := appmanage.NewAppManage(httpServer, grpcServer)
	return appManage
}
